Repository Ayushjhawar8/Flavor-ai, pull requests merged in 2025-07, with the labels that each got.

#20 Add "Back to Top" Button for Easier Navigation in README
  README.md
Labels: documentation, gssoc25, Level 1

#28 Improved UI/UX of cards
  app/page.jsx
Labels: enhancement, gssoc25, Level 2, Frontend

#26 Bug fix: Back Button Not Working on Mobile View
  components/BackButton.jsx
Labels: gssoc25, Level 1, Frontend

#38 Add: Basic Pull Request template
  .github/pull_request_template.md
Labels: gssoc25, Level 1

#52 fix : clear button now resets form and output correctly
  app/ai/page.jsx
  components/FormComponents.jsx
  components/GenerateRecipeForm.jsx
Labels: gssoc25, Level 2, 🚀 stellar contributor

#31 docs: add GSSoC'25 banner at the top of README
  README.md
Labels: gssoc25, Level 1

#59 Changed the background color of body and attached screenshot shows some visible dark color
  app/globals.css
Labels: gssoc25, Level 1, Frontend

#63 Fixed visibility in navbar
  app/page.jsx
  components/RecipeSearchBar.jsx
Labels: gssoc25, Level 2, Frontend, 🚀 stellar contributor

#43 Contribute on GitHub button in footer linking to project issues
  app/page.jsx
Labels: gssoc25, Level 1, Frontend

#78 [FEAT]: add issue tempaltes, bug, chore, documentation, feat and question
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/chore_request.yml
  .github/ISSUE_TEMPLATE/documentation.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
  .github/ISSUE_TEMPLATE/question.yml
Labels: documentation, enhancement, gssoc25, Level 1

#79 promt refined
  app/api/generate-recipe/route.js
Labels: enhancement, gssoc25, Level 2, Backend, 🚀 stellar contributor

#96 improve-search
  components/RecipeSearchBar.jsx
Labels: enhancement, gssoc25, Level 2, 🚀 stellar contributor

#112 [#99] show category suggestion on empty favouriate page
  app/favorite/page.tsx
Labels: enhancement, gssoc25, Level 2, Frontend

#114 Create CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: documentation, gssoc25, Level 1
