Repository Ayushjhawar8/Flavor-ai, pull requests merged in 2025-08, with the labels that each got.

#131 Resolved Mobile Layout Overflow in Cuisine Preference Section
  components/GenerateRecipeForm.jsx
  screenshots/after.png
  screenshots/before.png
Labels: bug, gssoc25, level 1, Frontend

#127 Update ThemeToggle.jsx
  components/ThemeToggle.jsx
Labels: enhancement, gssoc25, level 2, Frontend

#128 Update page.jsx
  app/page.jsx
Labels: gssoc25, level 2, Frontend

#141 [FEAT] UI Consistency Enhancement: Adopt the Pink Version for Search …
  app/globals.css
  components/RecipeSearchBar.jsx
Labels: enhancement, gssoc25, level 2, Frontend, 🚀 stellar contributor

#143 feat: Add AI Diet Planner with personalized meal plans
  .env.sample
  README.md
  app/api/generate-diet-plan/route.js
  app/api/test-diet-plan/route.js
  app/diet-planner/page.jsx
  app/page.jsx
  lib/diet-planner.test.js
  lib/schemas.js
Labels: enhancement, gssoc25, level 3, Backend, Frontend

#147 Fixed heading layout in cateory section
  app/category/[category]/page.tsx
  components/ShowMeal.jsx
Labels: bug, gssoc25, level 2, Frontend, 🚀 stellar contributor

#161 Fixed Font colors not visible on dark theme
  app/category/[category]/page.tsx
  app/favorite/page.tsx
  components/Footer.jsx
  components/ShowMeal.jsx
Labels: bug, enhancement, gssoc25, level 3, Frontend

#162 Multilingual Support
  app/globals.css
  app/layout.jsx
  components/GoogleTranslate.js
  components/GoogleTranslateWrapper.jsx
Labels: enhancement, gssoc25, level 3, Frontend, 🚀 stellar contributor

#164 Fix:- WRONG PULL REQUEST MERGED
  components/RecipeSearchBar.jsx
  components/ThemeToggle.jsx
Labels: bug, gssoc25, level 2, Frontend

#174 Inconsistent Layout in diet planner page fixed
  app/diet-planner/page.jsx
  components/Navbar.tsx
Labels: bug, gssoc25, level 2, Frontend, conflicts

#185 Added allergen info underneath the cuisine and added diet-based tag filtering
  app/page.jsx
  components/ShowMeal.jsx
Labels: enhancement, gssoc25, level 3, Frontend, 🚀 stellar contributor

#187 [ FEAT ]: Added a "Cursor Trail Effect "
  app/ai/page.jsx
  app/globals.css
  app/layout.jsx
  components/SnakeCursor.tsx
  package-lock.json
  package.json
Labels: enhancement, gssoc25, level 2, Frontend, conflicts

#196 ensure back button goes behind navbar when scrolling
  components/BackButton.tsx
Labels: bug, gssoc25, level 2, Frontend

#209 Update Readme with gssoc logo
  README.md
  screenshots/gssoc logo.png
Labels: documentation, enhancement, gssoc25, level 2, 🚀 stellar contributor

#221 Back button for diet planner
  app/diet-planner/page.jsx
Labels: enhancement, gssoc25, level 1, Frontend, 🚀 stellar contributor

#226 Text visibility issue in Dark Mode for Category Dishes Description
  app/page.jsx
Labels: enhancement, gssoc25, level 1, Frontend

#228 fix: update theme handling for dark/light mode in AI Recipe and Ingre…
  components/AiRecipe.jsx
  components/FormComponents.jsx
  components/IngredientSimilarity.jsx
Labels: enhancement, gssoc25, level 2, Frontend, 🚀 stellar contributor

#230 [FEAT] Highlight Ingredient text
  components/ShowMeal.jsx
Labels: enhancement, gssoc25, level 3, Frontend, 🚀 stellar contributor

#232 Fix build error (page.jsx → page.tsx) and confirm diet filter & table functionality
  app/page.jsx
  app/page.tsx
  components/RecipeSearchBar.tsx
Labels: bug, enhancement, gssoc25, level 3, Frontend

#233 Added a Home Button on the navbar that redirects back to the home page
  components/Navbar.tsx
Labels: enhancement, gssoc25, level 1, Frontend

#234 Add Diet Preference Dropdown (Vegetarian, Non-Vegetarian, Eggetarian, Vegan) to Diet Planner Form with Vegetarian toggle on the top
  app/diet-planner/page.jsx
Labels: enhancement, gssoc25, level 2, Frontend, 🚀 stellar contributor

#235 fix: resolve white corners in footer on dark mode
  app/category/[category]/page.tsx
  app/favorite/page.tsx
  components/ShowMeal.jsx
Labels: enhancement, gssoc25, level 1, Frontend

#237 Fix: Blur the background & search functionality consistently across all pages
  app/ai/page.jsx
  app/category/[category]/page.tsx
  app/diet-planner/page.jsx
  app/favorite/page.tsx
  components/Navbar.tsx
  components/ShowMeal.jsx
  package-lock.json
Labels: enhancement, gssoc25, level 3, Frontend

#238 Added more gender options (Other, Prefer not to say) in diet planner
  app/diet-planner/page.jsx
Labels: enhancement, gssoc25, level 1, Frontend
